[build]
  base = "facts-dashboard"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16.14.0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 