[build]
  base = "facts-dashboard"
  command = "CI=false npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"
  NEXT_IGNORE_TS_ERRORS = "true"
  PYTHON_VERSION = "3.9.14"

# Pengaturan untuk Next.js
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 